import type { menuItemType, menuType } from "../utils/entityTypes";

export const Menus: menuType[] = [
  {
    id: "1",
    name: "Coffee",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non eligendi necessitatibus illo inventore adipisci eos dolor accusantium totamaspernatur.",
    imgUrl: "coffee_url",
    maxNumOfSpecial: 2,
    numOfSpecials: 2,
    seasonal: false,
    season: null,
    active: true,
  },
  {
    id: "2",
    name: "Teas",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non eligendi necessitatibus illo inventore adipisci eos dolor accusantium totamaspernatur.",
    imgUrl: "teas_url",
    maxNumOfSpecial: 2,
    numOfSpecials: 2,
    seasonal: false,
    season: null,
    active: true,
  },
  {
    id: "3",
    name: "Smoothies",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Non eligendi necessitatibus illo inventore adipisci eos dolor accusantium totamaspernatur.",
    imgUrl: "smoothie_url",
    maxNumOfSpecial: 2,
    numOfSpecials: 2,
    seasonal: false,
    season: null,
    active: true,
  },
];

export const MenuItems: menuItemType[] = [
  {
    id: "1",
    name: "Latte",
    price: 2.5,
    menuId: "1",
    menu: "Coffee",
    special: true,
    mainIngredients: ["finest Coffee grains", "milk", "sugar"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "2",
    name: "Coffee",
    price: 1.5,
    menuId: "1",
    menu: "Coffee",
    special: true,
    mainIngredients: ["finest Coffee grains", "milk", "sugar"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "3",
    name: "Expresso",
    price: 2.5,
    menuId: "1",
    menu: "Coffee",
    special: true,
    mainIngredients: ["finest Coffee grains", "milk", "sugar"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "4",
    name: "Vanilla Latte",
    price: 2.6,
    menuId: "1",
    menu: "Coffee",
    special: false,
    mainIngredients: ["finest Coffee grains", "milk", "sugar"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "5",
    name: "Tea",
    price: 1.6,
    menuId: "2",
    menu: "Teas",
    special: true,
    mainIngredients: ["finest tea", "milk", "sugar"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "6",
    name: "Earl Gray",
    price: 2.4,
    menuId: "2",
    menu: "Teas",
    special: true,
    mainIngredients: ["finest tea", "milk", "sugar"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "7",
    name: "Roibois",
    price: 2.4,
    menuId: "2",
    menu: "Teas",
    special: false,
    mainIngredients: ["finest tea", "milk", "sugar"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "8",
    name: "Banana Smoothie",
    price: 3.4,
    menuId: "3",
    menu: "Smoothies",
    special: true,
    mainIngredients: ["bananas", "apples", "apple juice"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "9",
    name: "Strawberry Smoothie",
    price: 3.6,
    menuId: "3",
    menu: "Smoothies",
    special: true,
    mainIngredients: ["strawberries", "apples", "apple juice"],
    active: true,
    seasonal: false,
    season: null,
  },
  {
    id: "10",
    name: "Matcha Smoothie",
    price: 4.5,
    menuId: "3",
    menu: "Smoothies",
    special: false,
    mainIngredients: ["Matcha", "apples", "apple juice"],
    active: true,
    seasonal: false,
    season: null,
  },
];
